**Sesi 9 Introduction python for data science Hacktive8**

In [40]:
import numpy as np
import pandas as pd
import math
import statistics
import scipy.stats
from IPython.display import Math, Latex

Deskriptive statisctic untuk menyajikan informasi data <br>
Inferential statisctic untuk menyimpulkan data

Outlier terkait data yang tersaji <br> overfitting terkait model

Menangani outlier berbeda-beda, tergantung kasusnya <br>
Bisa di remove, transform log, atau milih data yang gaada outlier

Measure of Central tendency <br>
Mean, Modus, Median

In [2]:
x = [8,1,2.5,4,28]
x_with_nan = [8,1,2.5,np.nan,4,28]
print(x)
print(x_with_nan)

[8, 1, 2.5, 4, 28]
[8, 1, 2.5, nan, 4, 28]


In [3]:
mean_x = sum(x)/len(x)
mean_x

8.7

In [4]:
mean_stats = statistics.mean(x)
print(mean_stats)

8.7


In [5]:
mean_np = np.mean(x)
print(mean_np)

8.7


In [6]:
#Buat array (y) dan series (z) dari x
y,y_with_nan = np.array(x), np.array(x_with_nan)
z,z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y,y_with_nan)
print(z,z_with_nan)

[ 8.   1.   2.5  4.  28. ] [ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64 0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [7]:
z_with_nan.mean()

8.7

In [8]:
y_with_nan.mean()

nan

In [9]:
y.mean()

8.7

In [10]:
z.mean()

8.7

Weighted mean : Rata-rata dengan menghitung pembobotan

In [11]:
x = [8,1,2.5,4,28]
w = [0.1, 0.2, 0.3, 0.25, 0.15] #pembobotannya

y,z,w = np.array(x),pd.Series(z), np.array(w)

wmean = np.average(y, weights=w)
print(wmean)

6.95


Harmonic mean : sering dipakai untuk rata-rata rate, kecepatan <br>
$\frac{n}{\sum\limits^{n}_{i=0}\frac{1}{x_{i}}}$, dengan
i berjalan

In [12]:
hmean_stats = statistics.harmonic_mean(x)
print(hmean_stats)

2.7613412228796843


In [13]:
speed = [60,20]
hmean_stats2 =  statistics.harmonic_mean(speed)
print(hmean_stats2)

30.0


In [14]:
hmean_stats3 =  scipy.stats.hmean(speed)
print(hmean_stats3)

30.0


Gemotric mean <br>
$(x_{1} \cdot x_{2} \cdot \cdots x_{n})^{\frac{1}{n}}$

In [15]:
#aritmatic mean
x = 1000
x*=1.3
x*=1.5
x*=1.4
x

2730.0

In [16]:
#coba manual mean
x = 1000
x*=1.4
x*=1.4
x*=1.4
x

2743.9999999999995

In [17]:
gmean = (30*50*40)**(1/3)
gmean 

39.148676411688626

In [18]:
x = 1000
x*=1.39148676411688626
x*=1.39148676411688626
x*=1.39148676411688626
x

2694.24595178679

In [19]:
gmean_x =  scipy.stats.gmean(x)
print(gmean_x)

2694.245951786789


In [20]:
a = [1,2,4,8,9]
n = len(a)
median = a[2]
print(n)
print(median)

5
4


In [21]:
x = [8,1,2.5,4,28] #median selalu di sort terkecil dulu
np.median(x)

4.0

In [22]:
n = len(x)
round(0.5*(n-1)) #untuk mengambil indeks

2

In [23]:
#Pembuktian manual
n = len(x)
if n%2==1: #sorted untuk ngurutin data terkecil
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5*n)
    median_ = 0.5*(x_ord[index-1]+x_ord[index])
median_

4

In [24]:
c = [1,2,4,3]
n = len(c)
if n%2==1: #sorted untuk ngurutin data terkecil
    median_ = sorted(c)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(c), round(0.5*n)
    median_ = 0.5*(x_ord[index-1]+x_ord[index])
median_

2.5

In [25]:
u = [2,3,2,8,12]
mode_ = max((u.count(i),i)for i in set(u))[1] #[1] karena mau ambil nilainya, kalo [0] ambil jumlah datannya
print(mode_)

2


In [26]:
u.count(2) #untuk melihat jumlah angka yang sama

2

In [27]:
[(u.count(i),i)for i in set(u)]

[(1, 8), (2, 2), (1, 3), (1, 12)]

In [28]:
statistics.mode(u)

2

In [32]:
u_series = pd.Series(u)
u_series.mode()

0    2
dtype: int64

In [33]:
u_array = np.array(u)
statistics.mode(u_array)

2

Series akan mengabaikan NaN sedangkan List akan mempertimbangkan NaN

In [34]:
v = pd.Series([1,2,3,3,3,np.nan,np.nan,np.nan,np.nan])
v.mode()

0    3.0
dtype: float64

In [35]:
h = [1,2,3,3,3,np.nan,np.nan,np.nan,np.nan]
statistics.mode(h)

nan

Measure of spread/dispersion <br>
Standar deviasi, mean deviasi, variansi, range, percentil, quartil, skewnes, kurtosis, korelasi <br>
- Standar Deviasi : simpangan baku, pengukuran jarak rata-rata. Rumusunya untuk SD sample  $\sigma = \sqrt{\frac{1}{n-1}\sum\limits^{n}_{i=0}(x_{n} - \bar{x})^{2}}$ dan untuk SD populasi $\sigma =\sqrt{\frac{1}{n}\sum\limits^{n}_{i=0}(x_{n} - \bar{x})^{2}}$ <br>
- Mean deviasi : rata-rata perbedaan absolut antara tiap nilai. Rumusnya ($\frac{|x_{n} - \bar{x}|}{n}$), $x_{n}=$ suatu data, $\bar{x}=$ rata-rata, $n=$ jumlah data <br>
- Variansi : kuadrat jarak rata-rata. Rumusnya $(SD)^{2}$ <br>
- Range : perbedaan nilai terendah dan tertinggi <br>
- Persentil : cara merepresentasikan posisi suatu nilai dalam kumpulan data <br>
- Quartil : nilai yang membagi data menjadi beberapa quarter <br>
- Skewness : ukuran asimetri distribusi probabilitas, nilai kemiringan. <br> 
ekor (perbandingannya titik tertinggi) kiri lebih panjang dari ekor kanan, dan mean < mode, hasil sesuai rumus negatif : Negative skewness <br>
ekor (perbandingannya titik tertinggi) kanan lebih panjang dari ekor kiri, dan mean > mode, hasil sesuai rumus positif : Positive skewness<br>
Rumusnya untuk mode skewness $\frac{mean-mode}{SD}$, untuk median skewness $3\frac{mean-median}{SD}$ <br>
- Kurtosis : ukuran data bersifat banyak outlier <br>
Mesokurtic : distribusi yang memiliki kurtosis berdistribusi normal, yaitu nol. <br>
Leptokurtic : distribusi yang memiliki kurtosis > kurtosis berdistribusi normal <br>
Platykurtic : distribusi yang memiliki kurtosis < kurtosis berdistribusi normal <br>
Perbedaan skewness dengan kurtosis ialah skewness mengacu pada tingkat simetri, sedangkan kurtosis engacu pada tingkat keberadaan outlier dalam distribusi <br>
- Korelasi : Teknik statistik untuk menunjukkan kekuatan variabel yang terkait. <br>
r > 0 : semakin besar satu variabel, variabel lainnya makin besar. <br>
r < 0 : semakin besar satu variabel, variabel lainnya makin kecil <br>
r = 0 : tidak ada hubungan antar variabel <br>
r = 1 : kemungkinan nilai maksimum di r <br>
r = -1 : kemungkinan nilai minimum di r

Variansi sample $ = \frac{\sum\limits^{n}_{i=0}(x_{n} - \bar{x})^{2}}{n-1}$ <br> variansi populasi $ = \frac{\sum\limits^{n}_{i=0}(x_{n} - \bar{x})^{2}}{n}$

In [38]:
x = [8, 1, 2.5, 4, 28]
sorted(x)

[1, 2.5, 4, 8, 28]

In [39]:
n  = len(x)
mean_var = np.mean(x)
var_ = sum((item-mean_var)**2 for item in x ) / (n-1)
var_

123.19999999999999

In [41]:
var_stat = statistics.variance(x)
var_stat

123.2

In [42]:
var_np = np.var(x,ddof=1)
var_np

123.19999999999999

In [43]:
z = pd.Series(x)
z.var()

123.19999999999999

Standar deviasi $\sigma = \sqrt{Variansi}$

In [29]:
#Kuis 1 tim 4
x = [1,2,3,6,7,8,30,40,50]
n = len(x)
mean = sum(x)/n
var_ = sum((item - mean)**2 for item in x)/(n-1)
Sd_ = var_**(1/2)

print(var_)
print(Sd_)

345.25000000000006
18.58090417606205


In [45]:
var_np

123.19999999999999

In [47]:
stdev = var_np**(1/2)
stdev

11.099549540409285

In [48]:
stdev = np.sqrt(var_np) 
stdev

11.099549540409285

In [49]:
stdev = statistics.stdev(x)
stdev

11.099549540409287

In [50]:
stdev = np.std(x,ddof=1)
stdev

11.099549540409285

Rumus skewness : $\frac{\sum\limits^{n}_{i=0}(x_{i} - \bar{x})^{3}n}{(n-1)(n-2)\sigma^{3}}$

In [51]:
n = len(x)
mean = np.mean(x)
stdev = statistics.stdev(x)
skew_ = (sum((item - mean)**3 for item in x))*n / ((n-1)*(n-2)*(stdev**3))
skew_

1.947043227390592

In [52]:
scipy.stats.skew(x,bias=False)

1.9470432273905927

In [53]:
z = pd.Series(x)
z.skew()

1.9470432273905924

In [54]:
scipy.stats.skew(x_with_nan)

nan

In [55]:
z_with_nan = pd.Series(x_with_nan)
z_with_nan.skew()

1.9470432273905924

In [56]:
scipy.stats.skew(z_with_nan)

nan

In [57]:
x =[-5,-1.1,0.1,2,8,12.8,21,25.8,41]
np.percentile(x,5) #Percentile 5

-3.44

In [58]:
np.percentile(x,0)

-5.0

In [59]:
np.percentile(x,100)

41.0

In [60]:
np.percentile(x,90)

28.840000000000003

In [66]:
statistics.quantiles(x,n=1)

[]

In [61]:
statistics.quantiles(x,n=2)

[8.0]

In [65]:
np.median(x) #equivalen dengan quartil 2

8.0

In [62]:
statistics.quantiles(x,n=4)

[-0.5, 8.0, 23.4]

In [67]:
statistics.quantiles(x,n=4,method='inclusive')

[0.1, 8.0, 21.0]

In [68]:
np.quantile(x,0)

-5.0

In [69]:
np.quantile(x,1)

41.0

In [70]:
np.quantile(x,0.5)

8.0

In [71]:
x_with_nan = [-5, -1.1,np.nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]
x_with_nan

[-5, -1.1, nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [72]:
np.quantile(x_with_nan,0)

nan

In [73]:
np.nanquantile(x_with_nan,0.5)

8.0

In [74]:
np.quantile(x,[0.25,0.5,0.75])

array([ 0.1,  8. , 21. ])

In [75]:
np.percentile(x,[25,50,75])

array([ 0.1,  8. , 21. ])

In [77]:
np.ptp(x) #menghitung range x

46.0

In [78]:
quartiles = np.quantile(x,[0.25,0.75])
IQR = quartiles[1] - quartiles[0]
IQR #Interquartil range

20.9

In [80]:
result = scipy.stats.describe(x,ddof=1,bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [81]:
(result.variance)**(1/2)

15.12454774346805

In [82]:
result.minmax[1]-result.minmax[0]

46.0

In [83]:
result.skewness

0.9249043136685094

In [84]:
z = pd.Series(x)
z

0    -5.0
1    -1.1
2     0.1
3     2.0
4     8.0
5    12.8
6    21.0
7    25.8
8    41.0
dtype: float64

In [85]:
z.describe()

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

In [87]:
#Korelasi
x = list(range(-10,11))
y = [0 , 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_ar, y_ar = np.array(x),np.array(y)
x_s,y_s = pd.Series(x),pd.Series(y)

In [88]:
len(x)==len(y)

True

Kovarian

In [89]:
n = len(x)
mean_x = np.mean(x)
mean_y = np.mean(y)

cov_xy = (sum((x[item]-mean_x)*(y[item]-mean_y) for item in range(n)))/(n-1)
cov_xy

19.95

In [91]:
cov_matrix = np.cov(x,y) #Kalo di matriks, liat diagonal non utama
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [92]:
np.var(x,ddof=1)

38.5

In [93]:
np.var(y,ddof=1)

13.914285714285711

In [94]:
cov_xy = cov_matrix[0,1]
cov_xy

19.95

Korelasi koefisien, $r_{xy} = \frac{Cov(x,y)}{\sigma_{x}\sigma{y}}$

In [95]:
var_x = np.var(x,ddof=1)
var_y = np.var(y,ddof=1)
cov_xy
std_x = np.std(x,ddof=1)
std_y = np.std(y,ddof=1)
r = cov_xy / (std_x*std_y)
r

0.861950005631606

In [96]:
xy_corr = scipy.stats.pearsonr(x,y).statistic
xy_corr

0.861950005631606

In [97]:
corr_matrix = np.corrcoef(x,y)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [98]:
scipy.stats.linregress(x,y).rvalue

0.861950005631606

In [99]:
#Pada 2D Array
a = np.array([[1,1,1],
             [2,3,1],
             [4,9,2],
             [8,27,4],
             [16,1,1]])

In [100]:
np.mean(a)

5.4

In [102]:
np.median(a)

2.0

In [103]:
np.mean(a,axis=0)

array([6.2, 8.2, 1.8])

In [104]:
np.mean(a,axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [105]:
np.var(a,ddof=1)

53.40000000000001

In [106]:
np.var(a,ddof=1,axis=0)

array([ 37.2, 121.2,   1.7])

In [107]:
#Pada DataFrame
row_names = ['first','second','third','fourth','fifth']
col_names=['A','B','C']
df = pd.DataFrame(a,index=row_names,columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [108]:
np.mean(df.A)

6.2

In [109]:
df['A'].mean()

6.2

In [110]:
np.var(df,ddof=1)

A     37.2
B    121.2
C      1.7
dtype: float64

In [111]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [112]:
df.mean(axis=0)

A    6.2
B    8.2
C    1.8
dtype: float64

In [113]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64