**Sesi 4 Introduction python for data science Hacktive8**

In [3]:
import numpy as np

In [5]:
#Kuis 1
def tambah(a, b):
    return a + b

def kurang(a, b):
    return a - b

def kali(a, b):
    return a * b

def bagi(a, b):
    return a / b

def pangkat(a, b):
    return a ** b

while True:
    try:
        angka1 = int(input("Masukkan angka pertama: "))
        break
    except ValueError:
        print("Input salah")

operator = input("Masukkan pilihan operator: ")

while True:
    try:
        angka2 = int(input("Masukkan angka kedua: "))
        break
    except ValueError:
        print("Input salah")

if operator == '+':
    print(angka1, '+', angka2, '=', tambah(angka1, angka2))
elif operator == '-':
    print(angka1, '-', angka2, '=', kurang(angka1, angka2))
elif operator == 'x':
    print(angka1, 'x', angka2, '=', kali(angka1, angka2))
elif operator == ':':
    print(angka1, ':', angka2, '=', bagi(angka1, angka2))
elif operator == '^':
    print(angka1, '^', angka2, '=', pangkat(angka1, angka2))
else:
    print("Operator", operator, "tidak ditemukan")

Masukkan angka pertama: 4
Masukkan pilihan operator: -
Masukkan angka kedua: 2
4 - 2 = 2


In [4]:
c = np.array([1,2,3])
c

array([1, 2, 3])

fitur buat numpy <br>
np.array <br>
np.zeros <br>
np.empty <br>
np.random <br>
np.arrange( , , ) <br>
np.append <br>
np.delete <br>
np.sort <br>
n.dim *buat ukuran dimensi <br>
.size * jumlah elemen di array <br>
.reshape () <br> 
np.newaxis <br>
np.vstack <br>
np.expand_dims <br>

In [6]:
b = np.array ([[2, 3, 4]]) 
c = np.array ([2, 3, 4]) #terhitung 3 baris dan 1 kolom
print(b.shape)
print(c.shape)
np.arange(2,24,3)
print(np.arange(2,24,3))
np.vstack([b,c])
d = np.expand_dims(b,axis=1)
e = np.expand_dims(c,axis=0)
print(b[b>3])
print(d)
print(e)

(1, 3)
(3,)
[ 2  5  8 11 14 17 20 23]
[4]
[[[2 3 4]]]
[[2 3 4]]


In [9]:
n=int(input('Mau mulai dari berapa bintang nih ? '))
t=0

if n%2==0:
   t=n-1
else:
   t=n

for i in range(0,t):
   if (t-2*i)>0: 
      print('  '*i+'* '*(t-2*i))
   else:
      k=t-i-1
      print('  '*k+'* '*(t-2*k))

Mau mulai dari berapa bintang nih ? 6
* * * * * 
  * * * 
    * 
  * * * 
* * * * * 


In [11]:
#stack
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print('Stack secara Vertikal')
print(np.vstack([array_14,array_15]))
print('Stack secara Horizontal')
print(np.hstack([array_14,array_15]))

Stack secara Vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
Stack secara Horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [12]:
#hsplit
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [13]:
#vsplit
array_19 = np.array([[1,2,3,4],[4,5,6,7]])
print(array_19.shape)
print('Horizontal Split')
print(np.hsplit(array_19,2))
print('Vertical Split')
print(np.vsplit(array_19,2))

(2, 4)
Horizontal Split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
Vertical Split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


In [14]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [15]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_a.sum())
print(array_c.sum())
print(array_c.sum(axis=0))

6
21
[5 7 9]


In [16]:
array_c = np.array([[1,2,3],[4,5,6]])
print(array_c)
print(array_c.sum(axis=0))
print(array_c.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [17]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[5,2,3],[4,5,6]])
print(array_a.max())
print(array_c.max())
print(array_c)
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[[5 2 3]
 [4 5 6]]
[5 5 6]
[4 2 3]


.T untuk mentrasnpose

In [18]:
print(array_c.T)
print(array_c.T.shape)

[[5 4]
 [2 5]
 [3 6]]
(3, 2)


In [23]:
array_random = np.random.random([12,2])
print(array_random)

[[0.38446897 0.34244482]
 [0.65077083 0.25351737]
 [0.17556179 0.68890987]
 [0.50839576 0.84174345]
 [0.99227343 0.17468981]
 [0.50155769 0.43160944]
 [0.63901574 0.50240907]
 [0.97748631 0.57372321]
 [0.52956155 0.71941643]
 [0.95303531 0.87309179]
 [0.25725512 0.17163438]
 [0.82141128 0.70737983]]


In [26]:
np.square(13)

169

In [27]:
np.sqrt(8)

2.8284271247461903

In [28]:
a = np.log(1000000)
print(a)

13.815510557964274


In [29]:
np.exp(a)

999999.9999999995

In [10]:
def bil_prima(awal, akhir):
    prima = []
    for i in range(awal, akhir + 1):
        if i > 1:
            for j in range(2, i):
                if (i % j) == 0:
                    break
            else:
                prima.append(i)
    return prima
awal = int(input("Masukkan nilai awal : "))
akhir = int(input("Masukkan nilai akhir : "))
print(bil_prima(awal,akhir))

Masukkan nilai awal : 12
Masukkan nilai akhir : 89
[13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89]
